### ISSUE TITLE
Missing how to extract the Kickstart 1.2 file

### ISSUE THREAD

**Issue by Auster-South-Anemoi** [sigboe/extractwings#1]
From what I've tested, if you're on Linux/WSL, you can change the first command of the tutorial to this if you want the Kickstart 1.2 BIOS: `7z e -tzip -aos Wings.exe Kick12.rom -r`

You can probably get the Kickstart file with a GUI-based program such as Windows' 7zip as well. Or maybe you could add a new line after line 3 in the .bat file and add `7z e -tzip -aos -o"%mypath:~0,-1%" %* Kick12.rom -r`, but I didn't test the Windows version yet to see if doing it really extracts the Kickstart file.

And the Kickstart's md5sum should match the one listed in the BIOS part of PUAE's page on Libretro/Retroarch's site. Then you just need to rename it for what your emulator of choice expects.

**Comment by sigboe** [comment]
If you test this (it will probably work) then add it as a pull request, then I will accept the PR (after testing it my self). This way you get credit for it in the commit log and elsewhere. Feel free to add your name under the `# Credits` section in the readme as well if you want.

If not then I will probably do it when I have some time at a later date.

**Comment by Auster-South-Anemoi** [comment]
Hi! Just created 2 pull requests:
Pull requests #2 and #3 
I tried to polish the pull requests' new informations, but if you feel like there's room for improvement, feel free to edit it however you like.

**Comment by Auster-South-Anemoi** [comment]
I just missed something very small: near the end of README.md, I should've changed "3 lines of functional code" for "4 lines of functional code", since I added that line for extracting the firmware.
